types:
  - build
  - test
  - deploy

windows_types:
  type: build
  tags: 
    - windows
  script:
    - cd TypeInspection 
    - .\build.bat 
  after_script:
    - x64\Release\TypeInspection.exe
    - Release\TypeInspection.exe

build64_linux_types:
  type: build
  tags: 
    - linux64
  script:
    - cd TypeInspection
    - mkdir build-gcc
    - cd build-gcc
    - CC=gcc CXX=g++ cmake ..
    - make
    - cd ..
    - mkdir build-clang
    - cd build-clang
    - CC=clang CXX=clang++ cmake ..
    - make 
  after_script:
    - TypeInspection/build-clang/types
    - TypeInspection/build-gcc/types

build32_linux_types:
  type: build
  tags: 
    - linux32
  script:
    - cd TypeInspection
    - mkdir build-gcc
    - cd build-gcc
    - CC=gcc CXX=g++ cmake ..
    - make
    - cd ..
    - mkdir build-clang
    - cd build-clang
    - CC=clang CXX=clang++ cmake ..
    - make 
  after_script:
    - TypeInspection/build-clang/types
    - TypeInspection/build-gcc/types

  